# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'CavistaCodingTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CavistaCodingTest
  
  pod 'Alamofire', '~> 5.2'
  pod 'SnapKit', '~> 5.0'
  pod 'Kingfisher', '~> 5.14'
  pod 'GRDB.swift', '5.0.0-beta.6'
  pod 'ReachabilitySwift', '~> 5.0'
  pod 'ProgressHUD', '~> 13.4'

end
